---
service:
  addr: :8000
  debug:
    requests: true
    stacks: true
  log:
    prefix: "[service] "
  schema:
    enabled: true
    uri_path: /schema
    file_path: /path/to/schema
    file_pattern: schema.*
    root_redirect: true
  trace:
    enabled: true
    buffer: 100
    # YAML-based tracing
    recorder: yaml
    params: trace.yaml
    # DynamoDB-based tracing
    #recorder: dynamodb
    #params: us-west-2:Trace:access_key:secret_key
  version:
    min: 1
    max: 1