---
service:
  addr: :8000
  debug:
    requests: true
    stacks: true
    stack_size: 8192
  log:
    prefix: "[service] "
  schema:
    enabled: true
    uri_path: /schema
    file_path: /path/to/schema
    file_pattern: schema.*
    root_redirect: true
  trace:
    enabled: true
    buffer: 100
    recorder: yaml
    params:
      path: trace.yaml
  version:
    min: 1
    max: 1