---
service:
  addr: :8000
  debug:
    requests: true
    stacks: true
    stack_size: 8192
  log:
    prefix: "[service] "
  metrics:
    enabled: true
    server: 127.0.0.1:8125
    prefix: service.
    interval: 2s
  schema:
    enabled: true
    uri_path: /schema
    file_path: /path/to/schema
    file_pattern: schema.*
    root_redirect: true
  trace:
    enabled: true
    buffer: 100
    recorder: yaml
    params:
      path: trace.yaml
  transport:
    tls: false
    cert_file_path:
    key_file_path:
  version:
    min: 1
    max: 1